const HostState = {
    HOST_LOBBY: 'HOST_LOBBY',
    WAITING_FOR_QUESTIONS: 'WAITING_FOR_QUESTIONS',
    WAITING_FOR_ANSWERS: 'WAITING_FOR_ANSWERS',
    ALL_ANSWERS_RECEIVED: 'ALL_ANSWERS_RECEIVED',
    GAME_ENDED: 'GAME_ENDED'
};

export default HostState;