const HostState = {
    HOST_LOBBY: 'HOST_LOBBY',
    WAITING_FOR_QUESTIONS: 'WAITING_FOR_QUESTIONS',
    WAITING_FOR_ANSWERS: 'WAITING_FOR_ANSWERS',
    REVEAL: 'REVEAL',
    GAME_OVER: 'FINISHED'
};

export default HostState;
