const PlayerState = {
    CREATE_AVATAR: 'CREATE_AVATAR',
    LOBBY: 'LOBBY',
    WRITING_QUESTION: 'WRITING_QUESTION',
    WAITING_FOR_OTHER_PLAYERS: 'WAITING_FOR_OTHER_PLAYERS',
    WRITING_ANSWERS: 'WRITING_ANSWERS',
    GAME_OVER: 'GAME_OVER'
};

export default PlayerState;
