const PlayerState = {
    LOBBY: 'LOBBY',
    WRITING_QUESTION: 'WRITING_QUESTION',
    WAITING_FOR_OTHER_PLAYERS: 'WAITING_FOR_OTHER_PLAYERS',
    WRITING_ANSWERS: 'WRITING_ANSWERS'
};

export default PlayerState;
