const PlayerState = {
    LOBBY: 'LOBBY',
    WRITING_QUESTION: 'WRITING_QUESTION',
    WAITING_FOR_QUESTIONS: 'WAITING_FOR_QUESTONS',
    WRITING_ANSWERS: 'WRITING_ANSWERS',
    WAITING_FOR_ANSWERS: 'WAITING_FOR_ANSWERS'
};

export default PlayerState;
